name: survey_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.19.0

  # Firebase
  firebase_core: ^2.25.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_core_web: ^2.11.0
  firebase_auth_web: ^5.9.0
  firebase_storage_web: ^3.7.0
  cloud_firestore_web: ^3.10.0

  # UI Components
  flutter_speed_dial: ^7.0.0
  percent_indicator: ^4.2.3

  # Network & Connectivity
  connectivity_plus: ^5.0.2

  # Image & Media
  image_picker: ^1.0.7
  image_picker_web: ^3.1.1
  cached_network_image: ^3.3.0

  # Local Storage & Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # Utils
  uuid: ^4.2.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # Uncomment if you need to add assets
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Uncomment if you need custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
